#!/usr/bin/env python

import math
import rospy
from std_msgs.msg import Float64

def mover():
    pub_j1 = rospy.Publisher('/simple_arm/joint_1_position_controller/command',
                             Float64, queue_size=10)
    pub_j2 = rospy.Publisher('/simple_arm/joint_2_position_controller/command',
                             Float64, queue_size=10)
    rospy.init_node('clock')
    
    lag_duration = rospy.get_param('~clock_rate', 0.1) #0.1
    rate = rospy.Rate(int(1/lag_duration))  # rate=10
    start_time = 0

    while not start_time:
        start_time = rospy.Time.now().to_sec()

    while not rospy.is_shutdown():
        elapsed = rospy.Time.now().to_sec() - start_time
        #print("elaspsed: ", elapsed)
        angle_1 = math.pi
        angle_2 = elapsed # If rate is 10, clock will spin 180/pi degree per second.
        pub_j1.publish(angle_1)
        pub_j2.publish(angle_2)
        rate.sleep()

if __name__ == '__main__':
    try:
        mover()
    except rospy.ROSInterruptException:
        pass
